In [2]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])
result = arr1+arr2
print(result)

[[2 4 6]
 [5 7 9]]


In [9]:
data= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
data
print(np.argmax(data)) #index of maximum element

11


In [5]:
mean= data.mean(axis=0)
mean

array([5.5, 6.5, 7.5])

In [6]:
std=data.std(axis=0)
std

array([3.35410197, 3.35410197, 3.35410197])

In [7]:
normalized_data= (data-mean)/std
print(normalized_data)

[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]
