In [2]:
import numpy as np
myarr= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
print(myarr)
myarr.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [16]:
arr=np.array([[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
arr

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6],
       [7.7, 8.8, 9.9]])

In [15]:
print(arr.astype(int))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr[[[1,2]]]

array([[[4.4, 5.5, 6.6],
        [7.7, 8.8, 9.9]]])

In [20]:
myarr= np.array([1,2,3,4,5,6,7,8,9])
myarr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
even= myarr%2==0
even= myarr[myarr%2==0]
print (even)
print(even.astype(int))


[2 4 6 8]
[2 4 6 8]


In [28]:
myarr= np.array([1,2,3,4,5,6,7,8,9])

In [29]:
myarr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
myarr= np.array([1,26,73,44,25,86,17,58,89])
greater_50= myarr[myarr>50]
print(greater_50)

[73 86 58 89]


In [33]:
myarr= np.array([[1,26,73],[44,25,86],[17,58,89]])

In [34]:
greater_50= myarr[myarr>50]
print(greater_50)

[73 86 58 89]
