In [12]:
import numpy as np
myarr=np.array([1,2,3,4,4,5,6,7,7,8,9,0])


In [13]:
myarr

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 0])

In [15]:
myarr[[1,4,6]]

array([2, 4, 6])

In [16]:
myarr[myarr>3]

array([4, 4, 5, 6, 7, 7, 8, 9])