In [1]:
!pip install numpy


In [4]:
import numpy as np
arr = np.array([1,2,3])
print (arr)

[1 2 3]


In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full((4,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.arange(1,25,5)

array([ 1,  6, 11, 16, 21])

In [17]:
np.linspace(1,25,7)

array([ 1.,  5.,  9., 13., 17., 21., 25.])

In [21]:
myarr=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,0]]])

In [22]:
myarr

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [7, 8, 9, 0]]])

In [25]:
myarr.ndim

3

In [26]:
myarr.dtype

dtype('int32')